unbind "`"
bind "`" "toggleconsole"
developer "1"
_condebug "1"

[Console_Settings]
; Включаем консоль
console = "1"

[Key_Binds]
; Основная клавиша (тильда)
bind = "`" "toggleconsole"
; Запасная клавиша
bind = "p" "toggleconsole"

[Advanced]
; Размер буфера консоли (чтобы больше помещалось)
con_textsize = "2"
history_limit = "128"

unbind "`"
bind "`" "toggleconsole"
developer "1"
_condebug "1"
